# Generated by Django 4.1.7 on 2023-03-18 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricePrediction', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousePrices',
        ),
    ]
