# Generated by Django 4.1.7 on 2023-03-18 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricePrediction', '0004_houseprice_delete_houseprices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousePrice',
        ),
    ]
