# Generated by Django 4.1.7 on 2023-03-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricePrediction', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HousePrice',
        ),
    ]
