# Generated by Django 4.1.7 on 2023-03-24 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricePrediction', '0009_alter_houseprice_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseprice',
            name='resale_price_aft1year',
            field=models.FloatField(blank=True, null=True, verbose_name='resale_price_aft1year'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='resale_price_aft2year',
            field=models.FloatField(blank=True, null=True, verbose_name='resale_price_aft2year'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='resale_price_aft3year',
            field=models.FloatField(blank=True, null=True, verbose_name='resale_price_aft3year'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='resale_price_aft4year',
            field=models.FloatField(blank=True, null=True, verbose_name='resale_price_aft4year'),
        ),
        migrations.AddField(
            model_name='houseprice',
            name='resale_price_aft5year',
            field=models.FloatField(blank=True, null=True, verbose_name='resale_price_aft5year'),
        ),
    ]
