# Generated by Django 4.1.7 on 2023-03-25 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pricePrediction', '0009_alter_houseprice_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseprice',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
